import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import javax.swing.JFrame;   // import statement
// other imports you need, e.g.:
import javax.swing.JOptionPane;
import java.sql.*;

// then start the class
public class addNewPatientRecord extends javax.swing.JFrame {



    /**
     * Creates new form addNewPatientRecord
     */
    public addNewPatientRecord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtName = new javax.swing.JLabel();
        txtContact = new javax.swing.JLabel();
        txtAge = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        txtDisease = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Close.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 428, -1, -1));

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.setText("Name");
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        txtContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtContact.setText("Contact No");
        getContentPane().add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        txtAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAge.setText("Age");
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        txtGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtGender.setText("Gender");
        getContentPane().add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        txtBloodGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBloodGroup.setText("Blood Group");
        getContentPane().add(txtBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAddress.setText("Address");
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        txtDisease.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDisease.setText("Any Major Disease Suffered Earlier ");
        getContentPane().add(txtDisease, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 43, 200, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 83, 200, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 123, 200, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 163, 200, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 370, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save-icon--1.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 200, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to close this form and go back?",
        "Confirm Close",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        new home().setVisible(true); // Open Home page
        this.dispose(); // Close AddPatient window
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                                                                   
    try {
        // 1️⃣ Get text from JTextFields
        String name = jTextField1.getText().trim();       // Name
        String contact = jTextField2.getText().trim();    // Contact
        String gender = jTextField4.getText().trim();     // Gender
        String bloodGroup = jTextField5.getText().trim(); // Blood Group
        String address = jTextField6.getText().trim();    // Address
        String disease = jTextField7.getText().trim();    // Disease

        // 2️⃣ Validate age
        String ageText = jTextField3.getText().trim(); // Age input
        if(ageText.isEmpty() || !ageText.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid age!");
            return;
        }
        int age = Integer.parseInt(ageText);

        // 3️⃣ Validate blood group length
        if(bloodGroup.length() > 10) {
            JOptionPane.showMessageDialog(null, "Blood group too long! Max 10 characters.");
            return;
        }

        // 4️⃣ Connect to database
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();

        // 5️⃣ Insert into patient table
        st.executeUpdate("INSERT INTO patient(name, contact_no, age, gender, blood_group, address, disease) " +
                         "VALUES('" + name + "','" + contact + "'," + age + ",'" + gender + "','" + bloodGroup + "','" + address + "','" + disease + "')");

        // 6️⃣ Success message
        JOptionPane.showMessageDialog(null, "Patient added successfully!");

        // 7️⃣ Clear all fields
        jTextField1.setText(""); // Name
        jTextField2.setText(""); // Contact
        jTextField3.setText(""); // Age
        jTextField4.setText(""); // Gender
        jTextField5.setText(""); // Blood Group
        jTextField6.setText(""); // Address
        jTextField7.setText(""); // Disease

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.toString());
    }




    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtAge;
    private javax.swing.JLabel txtBloodGroup;
    private javax.swing.JLabel txtContact;
    private javax.swing.JLabel txtDisease;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
